[package]
name = "permissions"
version = "0.1.0"
authors = [
  "Spensa Nightshade <dev@skyward.finance>",
  "Mario Reder <mario.reder@pm.me>",
]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk.workspace = true
